# Generated by Django 4.2.3 on 2023-08-05 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_date_end'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='change_date',
            new_name='date_changed',
        ),
        migrations.AddField(
            model_name='project',
            name='is_open',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
